[workflows] benchmark: Add null_blk as backend block device driver
Signed-off-by: Free Ekanayaka <free@ekanayaka.io>

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -87,14 +87,18 @@ jobs:
         ppa:
           - main
           - stable
+        driver:
+          - nvme
+          - null_blk
         filesystem:
           - ext4
           - raw
     runs-on: ubuntu-22.04
     needs: bmc-deploy
     env:
-      FILESYSTEM: ${{ matrix.filesystem }}
       PPA: ${{ matrix.ppa }}
+      DRIVER: ${{ matrix.driver }}
+      FILESYSTEM: ${{ matrix.filesystem }}
       SSH: "ssh -o StrictHostKeyChecking=no -i ~/.ssh/bmc ubuntu@${{ needs.bmc-deploy.outputs.address}}"
     steps:
     - name: Setup SSH key
@@ -105,17 +109,30 @@ jobs:
     - name: Setup device
       id: setup
       run: |
-        device=/dev/nvme1n1
-        if $SSH sudo lsblk /dev/nvme1n1 -n -o MOUNTPOINTS | grep -q -e ^/$; then
-            device=/dev/nvme0n1
-        fi
-        partition=${device}p1
+        case $DRIVER in
+          nvme)
+            device=/dev/nvme1n1
+            if $SSH sudo lsblk /dev/nvme1n1 -n -o MOUNTPOINTS | grep -q -e ^/$; then
+              device=/dev/nvme0n1
+            fi
+            $SSH sudo apt-get install nvme-cli
+            $SSH sudo nvme format --force --lbaf=1 "${device}"
+            $SSH sudo parted "${device}" --script mklabel gpt
+            $SSH sudo parted -a optimal "${device}" --script mkpart primary ext4 2048 15GB
+            $SSH sudo partprobe
+            partition=${device}p1
+            ;;
+          null_blk)
+            $SSH sudo modprobe null_blk bs=4096 memory_backed=1 gb=1
+            device=${/dev/nullb0}
+            partition=${device}
+            ;;
+          *)
+            echo "error: unknown block device driver $DRIVER
+            exit 1
+            ;;
+        esac
         target=/mnt
-        $SSH sudo apt-get install nvme-cli
-        $SSH sudo nvme format --force --lbaf=1 "${device}"
-        $SSH sudo parted "${device}" --script mklabel gpt
-        $SSH sudo parted -a optimal "${device}" --script mkpart primary ext4 2048 15GB
-        $SSH sudo partprobe
         $SSH sudo add-apt-repository -y ppa:cowsql/$PPA
         $SSH sudo apt-get update -qq
         $SSH sudo apt-get install -qq -y libraft-tools xfsprogs
@@ -155,10 +172,18 @@ jobs:
       run: |
         if [ $FILESYSTEM != raw ]; then
           $SSH sudo umount ${{ steps.setup.outputs.target}}
-          if [ "$FILESYSTEM" = "zfs" ]; then
-            $SSH sudo zpool destroy -f cowsql
-          fi
         fi
+        case $DRIVER in
+          nvme)
+            ;;
+          null_blk)
+            $SSH sudo modprobe -r null_blk
+            ;;
+          *)
+            echo "error: unknown block device driver $DRIVER
+            exit 1
+            ;;
+        esac
         $SSH sudo apt-get purge -y libraft-tools libraft2
         $SSH sudo add-apt-repository -r -y ppa:cowsql/$PPA
 
