Re-enble support for decompressing snapshots
This is going to be needed for backward compatibility of existing deployments.

Signed-off-by: Free Ekanayaka <free@ekanayaka.io>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -74,8 +74,11 @@ jobs:
     - uses: actions/checkout@v3
     - name: Check that no optional dependency is installed
       run: |
+        # Remove liblz4-dev which is installed by default on the runner
+        sudo apt-get remove liblz4-dev
         # Check that there are no dependencies installed
         ! pkg-config --exists libuv
+        ! pkg-config --exists liblz4
 
     - name: Run autoreconf
       run: |
@@ -92,6 +95,12 @@ jobs:
         ! ./configure --enable-uv 2>errors
         tail -1 errors | grep -q "libuv required but not found" || (cat errors && false)
 
+    - name: With no deps ./configure --with-lz4
+      run: |
+        # Fail, since using lz4 makes sense only if libuv is used too.
+        ! ./configure --with-lz4 2>errors
+        tail -1 errors | grep -q "liblz4 can be used only if libuv is used too" || (cat errors && false)
+
     - name: Install libuv
       run: |
         sudo apt-get install -qq linux-libc-dev libuv1-dev
@@ -106,3 +115,29 @@ jobs:
         # Succeed, since libuv support can be disabled
         ./configure --disable-uv
 
+    - name: With libuv only ./configure --with-lz4
+      run: |
+        # Fail, since liblz4 is not installed.
+        ! ./configure --with-lz4 2>errors
+        tail -1 errors | grep -q "liblz4 required but not found" || (cat errors && false)
+
+    - name: With libuv only ./configure --disable-uv --with-lz4
+      run: |
+        # Fail, since using lz4 makes sense only if libuv is used too.
+        ! ./configure --disable-uv --with-lz4 2>errors
+        tail -1 errors | grep -q "liblz4 can be used only if libuv is used too" || (cat errors && false)
+
+    - name: Install liblz4
+      run: |
+        sudo apt-get install -qq liblz4-dev
+
+    - name: With libuv and liblz4 ./configure
+      run: |
+        # Succeed, since all optional dependencies are found and used.
+        ./configure
+
+    - name: With libuv and liblz4 ./configure --without-lz4
+      run: |
+        # Succeed, since we support building without lz4 even if both libuv and
+        # liblz4 are found.
+        ./configure --without-lz4
